### ISSUE TITLE
custom fonts are not loaded

### ISSUE THREAD

**Issue by tobiasbueschel** [preboot/angularjs-webpack#78]
I'm trying to use a custom font by referencing it in `app.css`. Unfortunately, it only works if I declare it in `index.html`. Maybe Webpack does not properly resolve the path?

**Not working:**
```css
/* app.css */

@font-face {
   font-family: "CustomFont";
   src: url(/fonts/Custom-Font.otf) format("opentype");
}
```

**Working:**
```css
/* index.html */

<style type="text/css">
@font-face {
   font-family: "CustomFont";
   src: url(/fonts/Custom-Font.otf) format("opentype");
}
</style>
```
